"""create profile table

Revision ID: 9f8602c87159
Revises: 
Create Date: 2026-03-30 22:31:42.289352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8602c87159'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('following')
    op.drop_table('media')
    op.drop_table('tweets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['profile.id'], name=op.f('tweets_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tweets_pkey'))
    )
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('media_pkey'))
    )
    op.create_table('following',
    sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followers_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followers_id'], ['profile.id'], name=op.f('following_followers_id_fkey')),
    sa.ForeignKeyConstraint(['following_id'], ['profile.id'], name=op.f('following_following_id_fkey'))
    )
    op.create_table('likes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tweet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], name=op.f('likes_tweet_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], name=op.f('likes_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'tweet_id', name=op.f('likes_pkey'))
    )
    # ### end Alembic commands ###
