"""create following association table

Revision ID: f3d9b58c2f3d
Revises: 9f8602c87159
Create Date: 2026-03-30 22:34:15.986207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d9b58c2f3d'
down_revision: Union[str, Sequence[str], None] = '9f8602c87159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('following_id', sa.Integer(), nullable=True),
    sa.Column('followers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followers_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['profile.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('following')
    # ### end Alembic commands ###
